useHelm3: true
allowNamespaceDiscovery: true
ingress:
  enabled: true
  certManager: true
  hostname:
  tls: true
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: "contour"
    cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
    kubernetes.io/tls-acme: "true"

# Auth Proxy for OIDC support
# ref: https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md
authProxy:
   enabled: true
   provider: oidc
   cookieSecret: bm90LWdvb2Qtc2VjcmV0Cg==
   clientID: kubeapps
   clientSecret: FOO_SECRET

# Pinniped Support
# https://liveandletlearn.net/post/kubeapps-on-tanzu-kubernetes-grid-13-part-2/
pinnipedProxy:
  enabled: true
  defaultAuthenticatorName: kubeapps-jwt-authenticator
  image:
    repository: bitnami/kubeapps-pinniped-proxy

clusters:
  - name: default
    pinnipedConfig:
      enable: true

apprepository:
  initialRepos:
    - name: vac-repo
      url: https://charts.app-catalog.vmware.com/demo
